/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#001230",
        "inverse-on-surface": "#1d3052",
        "tertiary": "#f2c01f",
        "outline": "#988e99",
        "on-secondary": "#452059",
        "on-primary-container": "#f2f5ff",
        "primary-fixed": "#d6e3ff",
        "secondary": "#e4b5fa",
        "outline-variant": "#4c444e",
        "primary-fixed-dim": "#a8c8ff",
        "surface-tint": "#a8c8ff",
        "on-background": "#d7e2ff",
        "surface-variant": "#213557",
        "primary-container": "#186fcf",
        "error": "#ffb4ab",
        "tertiary-container": "#d2a500",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-primary": "#003062",
        "inverse-surface": "#d7e2ff",
        "on-tertiary": "#3d2e00",
        "on-secondary-container": "#d2a4e8",
        "on-surface-variant": "#cec3cf",
        "secondary-fixed": "#f5d9ff",
        "secondary-fixed-dim": "#e4b5fa",
        "inverse-primary": "#005eb4",
        "surface-container-high": "#152a4b",
        "surface": "#001230",
        "on-tertiary-container": "#503d00",
        "surface-container-lowest": "#000d27",
        "primary": "#a8c8ff",
        "surface-container": "#091f41",
        "surface-dim": "#001230",
        "secondary-container": "#5d3772",
        "on-surface": "#d7e2ff",
        "surface-container-highest": "#213557",
        "surface-container-low": "#041b3c",
        "tertiary-fixed": "#ffdf91",
        "surface-bright": "#26395c",
        "board-purple": "#824b85",
        "board-yellow": "#7a5c00",
        "board-green": "#1d5e35",
        "board-dark": "#101204",
        "trello-blue": "#0c66e4",
        "trello-blue-hover": "#0055cc",
        "nav-dark": "#1d1b20",
        "card-bg": "#22272b",
        "card-border": "#333c44",
        "text-subtle": "#b6c2cf",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
